package fr.vn.galaxycore;

import cpw.mods.fml.client.registry.ClientRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import fr.vn.galaxycore.items.*;
import fr.vn.galaxycore.items.register.ArmorTest;
import fr.vn.galaxycore.items.register.BaseArmor;
import fr.vn.galaxycore.items.registerblockmodels.BlockPilarA;
import fr.vn.galaxycore.items.registerblockmodels.BlockPilarB;
import fr.vn.galaxycore.items.registerblockmodels.BlockTable;
import fr.vn.galaxycore.model.PilarAbajoModel;
import fr.vn.galaxycore.model.PilarArribaModel;
import fr.vn.galaxycore.model.PilarMedioModel;
import fr.vn.galaxycore.model.TableModel;
import fr.vn.galaxycore.ores.*;
import fr.vn.galaxycore.render.*;
import fr.vn.galaxycore.render.renderblocks.TileEntityPilarA;
import fr.vn.galaxycore.render.renderblocks.TileEntityPilarB;
import fr.vn.galaxycore.render.renderblocks.TileEntityPilarC;
import fr.vn.galaxycore.render.renderblocks.TileEntityTable;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraftforge.client.MinecraftForgeClient;
import net.minecraftforge.common.util.EnumHelper;

public class LoaderItems {
    public static Item pizza;
    public static Item sageInsectSoup;
    public static Item scytheHidani;
    public static Item shakujoObitoMadara;
    public static Item shakujoObito;
    public static Item woodKatana;
    public static Item arakLegs;
    public static Item arakChest;
    public static Item arakBoots;
    public static Item babyVegetaBoots;
    public static Item babyVegetaLegs;
    public static Item babyVegetaChest;
    public static Item champaBoots;
    public static Item champaLegs;
    public static Item champaChest;
    public static Item chiraiLegs;
    public static Item chiraiBoots;
    public static Item chiraiChest;
    public static Item daishinkanChest;
    public static Item daishinkanBoots;
    public static Item daishinkanLegs;
    public static Item fuBoots;
    public static Item fuLegs;
    public static Item fuChest;
    public static Item gogetaBoots;
    public static Item gogetaLegs;
    public static Item gogetaChest;
    public static Item kambaBoots;
    public static Item kambaChest;
    public static Item kambaLegs;
    public static Item shallotLegs;
    public static Item shallotChest;
    public static Item shallotBoots;
    public static Item trunksABoots;
    public static Item trunksALegs;
    public static Item trunksAChest;
    public static Item trunksBBoots;
    public static Item trunksBChest;
    public static Item trunksBLegs;
    public static Item trunksCBoots;
    public static Item trunksCLegs;
    public static Item trunksCChest;
    public static Item yardratLegs;
    public static Item yardratChest;
    public static Item yardratBoots;
    public static Item zenoSamaBoots;
    public static Item zenoSamaLegs;
    public static Item zenoSamaChest;
    public static Block VacaOre;
    public static Item VacaIngot;
    public static Block PigmanOre;
    public static Item PigmanIngot;
    public static Block SlimeOre;
    public static Item SlimeIngot;
    public static Block OvejaOre;
    public static Item OvejaIngot;
    public static Block MurcielagoOre;
    public static Item MurcielagoIngot;
    public static Block FantasmaOre;
    public static Item FantasmaIngot;
    public static Block MagmaOre;
    public static Item MagmaIngot;
    public static Block WhiterOre;
    public static Item WhiterIngot;
    public static Block GhastOre;
    public static Item GhastIngot;
    public static Block EndermanOre;
    public static Item EndermanIngot;
    public static Block CreeperOre;
    public static Item CreeperIngot;
    public static Block CerdoOre;
    public static Item CerdoIngot;
    public static Block BlazeOre;
    public static Item BlazeIngot;
    public static Block BrujaOre;
    public static Item BrujaIngot;
    public static Item AranaIngot;
    public static Block AranaOre;
    public static Block pilarabajo;
    public static Block pilarmedio;
    public static Block pilararriba;
    public static Item mjolnir;
    public static Item mandoblemodel;
    public static Block table;
    public static Item ColmilloDragon;
    public static Item hachamodel;
    public static Item stormbreaker;
    public static Item espadasparrow;
    public static Item picomodel;
    public static Item EspadaGalaxy;
    public static Item Lanza;
    public static Item cubito;
    public static Item blazeChest;
    public static Item blazeLegs;
    public static Item blazeBoots;
    public static Item crystalChest;
    public static Item crystalLegs;
    public static Item crystalBoots;
    public static Item crystalHelmet;
    public static Item magmaChest;
    public static Item magmaLegs;
    public static Item magmaBoots;
    public static Item magmaHelmet;
    public static Item protectorChest;
    public static Item protectorLegs;
    public static Item protectorBoots;
    public static Item protectorHelmet;
    public static Item dragonslayerChest;
    public static Item dragonslayerLegs;
    public static Item dragonslayerBoots;
    public static Item zombiePickaxe;
    public static Item steelPickaxe;
    public static Item raiderAxe;
    public static Item steelAxe;
    public static Item jungleAxe;
    public static Item emeraldBlade;
    public static Item earthShard;
    public static Item galaxySword;
    public static Item allXP;
    public static Item combatXP;
    public static Item colossalXP;
    public static Item grandBottle;
    public static Item yellowRock;
    public static Item capsula1;
    public static Item capsula2;
    public static Item capsula3;
    public static Item capsula4;
    public static Item esfera;
    public static Item whissSword;
    public static Item galaxyIngot;
    public static Item espadalapizlazuli;
    public static Item espadaacero;
    public static Item cuchillaacero;
    public static Block galaxyOre;
    public static Item calabazaHelmet;
    public static Item calabazaChest;
    public static Item calabazaLegs;
    public static Item calabazaBoots;
    public static Item mixedIngot;
    public static Item skeletonHelmet;
    public static Item skeletonChest;
    public static Item skeletonLegs;
    public static Item skeletonBoots;
    public static Block mixedOre;
    public static Block skeletonOre;
    public static Item skeletonIngot;
    public static Item TridenteHalloween;
    public static Item Daga;
    public static Item AxeHalloween;
    public static Item Azada;
    public static Item itHelmet;
    public static Item itChest;
    public static Item itLegs;
    public static Item scaryHelmet;
    public static Item scaryChest;
    public static Item scaryLegs;
    public static Item tropaHelmet;
    public static Item tropaBoots;
    public static Item tropaLegs;
    public static Item tropaChest;
    public static Item scaryBoots;
    public static Item itBoots;
    public static Item PiruletaHalloween;
    public static Item trunksChest;
    public static Item trunksLegs;
    public static Item trunksBoots;
    public static Item covidChest2;
    public static Item covidChest;
    public static Item covidLegs;
    public static Item covidBoots;
    public static Item covidHelmet;
    public static Item brokenChip;
    public static Item brokenProcessor;
    public static Item blueClothingFragment;
    public static Item redClothingFragment;
    public static Item armorFragment;
    public static Item swordFragment;
    public static final String MODID = "galaxycore";
    public static final String VERSION = "1.0";
    public static final ItemArmor.ArmorMaterial testArmorMaterial;
    public static final Item.ToolMaterial testToolMaterial;

        public static void init() {
            pizza = new AllPlainItems().setTextureName("galaxycore:pizza").setMaxDamage(0).setCreativeTab(CreativeTabs.tabMaterials);
            sageInsectSoup = new SwordStuff(testToolMaterial).setTextureName("galaxycore:SageInsectSoup").setUnlocalizedName("sageInsectSoup").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
            scytheHidani = new SwordStuff(testToolMaterial).setTextureName("galaxycore:scytheHidani").setUnlocalizedName("scytheHidani").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
            shakujoObitoMadara = new SwordStuff(testToolMaterial).setTextureName("galaxycore:ShakujoMadara1_1").setUnlocalizedName("shakujoObitoMadara").setCreativeTab(CreativeTabs.tabCombat).setMaxDamage(0);
            shakujoObito = new SwordStuff(testToolMaterial).setTextureName("galaxycore:ShakujoObito1_1").setUnlocalizedName("shakujoObito").setCreativeTab(CreativeTabs.tabCombat).setMaxDamage(0);
            woodKatana = new SwordStuff(testToolMaterial).setTextureName("galaxycore:woodKatana").setUnlocalizedName("woodKatana").setCreativeTab(CreativeTabs.tabCombat).setMaxDamage(0);
        arakChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:armor.arakChest").setUnlocalizedName("arakChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        arakLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.arakLeg").setUnlocalizedName("arakLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        arakBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.arakBoot").setUnlocalizedName("arakBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        babyVegetaChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:armor.bvegetaChest").setUnlocalizedName("babyvegetaChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        babyVegetaLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.bvegetaLeg").setUnlocalizedName("babyvegetaLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        babyVegetaBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.bvegetaBoot").setUnlocalizedName("babyvegetaBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        champaChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:armor.champaChest").setUnlocalizedName("champaChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        champaLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.champaLeg").setUnlocalizedName("champaLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        champaBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.champaBoot").setUnlocalizedName("champaBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        chiraiChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:armor.chiraiChest").setUnlocalizedName("chiraiChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        chiraiLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.chiraiLeg").setUnlocalizedName("chiraiLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        chiraiBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.chiraiBoot").setUnlocalizedName("chiraiBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        daishinkanChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:armor.daishinkanChest").setUnlocalizedName("daishinkanChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        daishinkanLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.daishinkanLeg").setUnlocalizedName("daishinkanLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        daishinkanBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.daishinkanBoot").setUnlocalizedName("daishinkanBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        fuChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:armor.fuChest").setUnlocalizedName("fuChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        fuLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.fuLeg").setUnlocalizedName("fuLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        fuBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.fuBoot").setUnlocalizedName("fuBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        gogetaChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:armor.gogetaChest").setUnlocalizedName("gogetaChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        gogetaLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.gogetaLeg").setUnlocalizedName("gogetaLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        gogetaBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.gogetaBoot").setUnlocalizedName("gogetaBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        kambaChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:armor.kambaChest").setUnlocalizedName("kambaChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        kambaLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.kambaLeg").setUnlocalizedName("kambaLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        kambaBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.kambaBoot").setUnlocalizedName("kambaBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        shallotChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:armor.shallotChest").setUnlocalizedName("shallotChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        shallotLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.shallotLeg").setUnlocalizedName("shallotLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        shallotBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.shallotBoot").setUnlocalizedName("shallotBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        trunksAChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:armor.trunksAChest").setUnlocalizedName("trunksAChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        trunksALegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.trunksALeg").setUnlocalizedName("trunksALegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        trunksABoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.trunksABoot").setUnlocalizedName("trunksABoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        trunksBChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:armor.trunksBChest").setUnlocalizedName("trunksBChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        trunksBLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.trunksBLeg").setUnlocalizedName("trunksBLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        trunksBBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.trunksBBoot").setUnlocalizedName("trunksBBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        trunksCChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:armor.trunksCChest").setUnlocalizedName("trunksCChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        trunksCLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.trunksCLeg").setUnlocalizedName("trunksCLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        trunksCBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.trunksCBoot").setUnlocalizedName("trunksCBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        yardratChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:armor.yardratChest").setUnlocalizedName("yardratChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        yardratLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.yardratLeg").setUnlocalizedName("yardratLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        yardratBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.yardratBoot").setUnlocalizedName("yardratBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        zenoSamaChest = new CommonArmor(testArmorMaterial, 0 , 1).setTextureName("galaxycore:armor.zenosamaChest").setUnlocalizedName("zenoSamaChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        zenoSamaLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:armor.zenosamaLeg").setUnlocalizedName("zenoSamaLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        zenoSamaBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:armor.zenosamaBoot").setUnlocalizedName("zenoSamaBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        covidHelmet = new CommonArmor(testArmorMaterial, 0, 0).setTextureName("galaxycore:covid_helmet").setUnlocalizedName("covidHelm").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        covidChest2 = new BaseArmor(setArmor(-1), 1, "covidChest", "covidChest").setCreativeTab(CreativeTabs.tabMaterials);
        covidBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:covid_boots").setUnlocalizedName("covidBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        covidChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:covid_chestplate").setUnlocalizedName("covidChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        covidLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:covid_leggins").setUnlocalizedName("covidLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        tropaHelmet = new CommonArmor(testArmorMaterial, 0, 0).setTextureName("galaxycore:tropa_helmet").setUnlocalizedName("tropaHelm").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        tropaChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:tropa_chestplate").setUnlocalizedName("tropaChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        tropaLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:tropa_leggins").setUnlocalizedName("tropaLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        tropaBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:tropa_boots").setUnlocalizedName("tropaBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        trunksChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:trunks_chestplate").setUnlocalizedName("trunksChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        trunksLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:trunks_leggins").setUnlocalizedName("trunksLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        trunksBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:trunks_boots").setUnlocalizedName("trunksBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        scaryHelmet = new CommonArmor(testArmorMaterial, 0, 0).setTextureName("galaxycore:scary_helmet").setUnlocalizedName("scaryHelm").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        scaryChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:scary_chestplate").setUnlocalizedName("scaryChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        scaryLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:scary_leggins").setUnlocalizedName("scaryLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        scaryBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:scary_boots").setUnlocalizedName("scaryBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        itHelmet = new CommonArmor(testArmorMaterial, 0, 0).setTextureName("galaxycore:it_helmet").setUnlocalizedName("itHelm").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        itChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:it_chestplate").setUnlocalizedName("itChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        itLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:it_leggins").setUnlocalizedName("itLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        itBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:it_boots").setUnlocalizedName("itBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        skeletonHelmet = new CommonArmor(testArmorMaterial, 0, 0).setTextureName("galaxycore:skeleton_helmet").setUnlocalizedName("skeletonHelm").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        skeletonChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:skeleton_chestplate").setUnlocalizedName("skeletonChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        skeletonLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:skeleton_leggins").setUnlocalizedName("skeletonLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        skeletonBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:boots_skeleton").setUnlocalizedName("skeletonBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        calabazaHelmet = new CommonArmor(testArmorMaterial, 0, 0).setTextureName("galaxycore:calabaza_helmet").setUnlocalizedName("calabazaHelm").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        calabazaChest = new CommonArmor(testArmorMaterial, 0, 1).setTextureName("galaxycore:calabaza_chestplate").setUnlocalizedName("calabazaChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        calabazaLegs = new CommonArmor(testArmorMaterial, 0, 2).setTextureName("galaxycore:calabaza_leggins").setUnlocalizedName("calabazaLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        calabazaBoots = new CommonArmor(testArmorMaterial, 0, 3).setTextureName("galaxycore:calabaza_boots").setUnlocalizedName("calabazaBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        blazeBoots = new ItemBlazeBoots(testArmorMaterial, 0, 3).setTextureName("galaxycore:blaze_boots").setUnlocalizedName("BlazeBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        blazeChest = new ItemBlazeBoots(testArmorMaterial, 0, 1).setTextureName("galaxycore:blaze_chestplate").setUnlocalizedName("BlazeChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        blazeLegs = new ItemBlazeBoots(testArmorMaterial, 0, 2).setTextureName("galaxycore:blaze_leggings").setUnlocalizedName("BlazeLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        crystalBoots = new ItemCrystalBoots(testArmorMaterial, 0, 3).setTextureName("galaxycore:crystal_boots").setUnlocalizedName("CrystalBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        crystalChest = new ItemCrystalBoots(testArmorMaterial, 0, 1).setTextureName("galaxycore:crystal_chestplate").setUnlocalizedName("CrystalChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        crystalLegs = new ItemCrystalBoots(testArmorMaterial, 0, 2).setTextureName("galaxycore:crystal_leggings").setUnlocalizedName("CrystalLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        crystalHelmet = new ItemCrystalBoots(testArmorMaterial, 0, 0).setTextureName("galaxycore:crystal_helm").setUnlocalizedName("CrystalHelm").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        magmaBoots = new ItemMagmaBoots(testArmorMaterial, 0, 3).setTextureName("galaxycore:magma_boots").setUnlocalizedName("MagmaBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        magmaChest = new ItemMagmaBoots(testArmorMaterial, 0, 1).setTextureName("galaxycore:magma_chestplate").setUnlocalizedName("MagmaChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        magmaLegs = new ItemMagmaBoots(testArmorMaterial, 0, 2).setTextureName("galaxycore:magma_leggings").setUnlocalizedName("MagmaLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        magmaHelmet = new ItemMagmaBoots(testArmorMaterial, 0, 0).setTextureName("galaxycore:magma_helmet").setUnlocalizedName("MagmaHelm").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        protectorBoots = new ItemProtectorBoots(testArmorMaterial, 0, 3).setTextureName("galaxycore:protector_boots").setUnlocalizedName("ProtectorBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        protectorChest = new ItemProtectorBoots(testArmorMaterial, 0, 1).setTextureName("galaxycore:protector_chestplate").setUnlocalizedName("ProtectorChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        protectorLegs = new ItemProtectorBoots(testArmorMaterial, 0, 2).setTextureName("galaxycore:protector_leggings").setUnlocalizedName("ProtectorLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        protectorHelmet = new ItemProtectorBoots(testArmorMaterial, 0, 0).setTextureName("galaxycore:protector_helmet").setUnlocalizedName("ProtectorHelm").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        dragonslayerBoots = new ItemDragonslayerBoots(testArmorMaterial, 0, 3).setTextureName("galaxycore:dragon2_boots").setUnlocalizedName("DragonslayerBoots").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        dragonslayerChest = new ItemDragonslayerBoots(testArmorMaterial, 0, 1).setTextureName("galaxycore:dragon2_chestplate").setUnlocalizedName("DragonslayerChest").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        dragonslayerLegs = new ItemDragonslayerBoots(testArmorMaterial, 0, 2).setTextureName("galaxycore:dragon2_leggins").setUnlocalizedName("DragonslayerLegs").setMaxDamage(0).setCreativeTab(CreativeTabs.tabCombat);
        zombiePickaxe = new ZombieAndRaiderStuff(testToolMaterial).setTextureName("galaxycore:zombie_pick").setUnlocalizedName("ZombiePickaxe").setCreativeTab(CreativeTabs.tabTools).setMaxDamage(0);
        steelPickaxe = new ZombieAndRaiderStuff(testToolMaterial).setTextureName("galaxycore:steel_pickaxe").setUnlocalizedName("SteelPickaxe").setCreativeTab(CreativeTabs.tabTools).setMaxDamage(0);
        raiderAxe = new SteelStuff(testToolMaterial).setTextureName("galaxycore:raider_axe").setUnlocalizedName("RaiderAxe").setCreativeTab(CreativeTabs.tabTools).setMaxDamage(0);
        steelAxe = new SteelStuff(testToolMaterial).setTextureName("galaxycore:steel_axe").setUnlocalizedName("SteelAxe").setCreativeTab(CreativeTabs.tabTools).setMaxDamage(0);
        jungleAxe = new SteelStuff(testToolMaterial).setTextureName("galaxycore:jungleaxe").setUnlocalizedName("JungleAxe").setCreativeTab(CreativeTabs.tabTools).setMaxDamage(0);
        Azada = new SteelStuff(testToolMaterial).setTextureName("galaxycore:Azada").setUnlocalizedName("Azada").setCreativeTab(CreativeTabs.tabTools).setMaxDamage(0);
        Daga = new SteelStuff(testToolMaterial).setTextureName("galaxycore:Daga").setUnlocalizedName("Daga").setCreativeTab(CreativeTabs.tabTools).setMaxDamage(0);
        AxeHalloween = new SteelStuff(testToolMaterial).setTextureName("galaxycore:axe_halloween").setUnlocalizedName("Axe Halloween").setCreativeTab(CreativeTabs.tabTools).setMaxDamage(0);
        TridenteHalloween = new SteelStuff(testToolMaterial).setTextureName("galaxycore:tridente_halloween").setUnlocalizedName("Tridente Halloween").setCreativeTab(CreativeTabs.tabTools).setMaxDamage(0);
        emeraldBlade = new SwordStuff(testToolMaterial).setTextureName("galaxycore:emerald_blade").setUnlocalizedName("EmeraldBlade").setCreativeTab(CreativeTabs.tabCombat).setMaxDamage(0);
        earthShard = new SwordStuff(testToolMaterial).setTextureName("galaxycore:earth_shard").setUnlocalizedName("EarthShard").setCreativeTab(CreativeTabs.tabCombat).setMaxDamage(0);
        galaxySword = new SwordStuff(testToolMaterial).setTextureName("galaxycore:galaxy_sword").setUnlocalizedName("GalaxySword").setCreativeTab(CreativeTabs.tabCombat).setMaxDamage(0);
        espadalapizlazuli = new SwordStuff(testToolMaterial).setTextureName("galaxycore:espadalapizlazuli").setUnlocalizedName("espadalapizlazuli").setCreativeTab(CreativeTabs.tabCombat).setMaxDamage(0);
        espadaacero = new SwordStuff(testToolMaterial).setTextureName("galaxycore:espadaacero").setUnlocalizedName("espadaacero").setCreativeTab(CreativeTabs.tabCombat).setMaxDamage(0);
        cuchillaacero = new SwordStuff(testToolMaterial).setTextureName("galaxycore:cuchillaacero").setUnlocalizedName("cuchillaacero").setCreativeTab(CreativeTabs.tabCombat).setMaxDamage(0);
        whissSword = new SwordStuff(testToolMaterial).setTextureName("galaxycore:whiss_sword").setUnlocalizedName("WhissSword").setCreativeTab(CreativeTabs.tabCombat).setMaxDamage(0);
        allXP = new AllPlainItems().setTextureName("galaxycore:allxp").setUnlocalizedName("AllXP");
        combatXP = new AllPlainItems().setTextureName("galaxycore:combat_xp").setUnlocalizedName("CombatXP");
        colossalXP = new AllPlainItems().setTextureName("galaxycore:colossal_xp").setUnlocalizedName("ColossalXP");
        grandBottle = new AllPlainItems().setTextureName("galaxycore:grand_bottle").setUnlocalizedName("GrandBottle");
        yellowRock = new AllPlainItems().setTextureName("galaxycore:yellow_rock").setUnlocalizedName("YellowRock");
        capsula1 = new AllPlainItems().setTextureName("galaxycore:capasula1").setUnlocalizedName("Capsula1");
        capsula2 = new AllPlainItems().setTextureName("galaxycore:capsula2").setUnlocalizedName("Capsula2");
        capsula3 = new AllPlainItems().setTextureName("galaxycore:capsula3").setUnlocalizedName("Capsula3");
        capsula4 = new AllPlainItems().setTextureName("galaxycore:capsula4").setUnlocalizedName("Capsula4");
        blueClothingFragment = new AllPlainItems().setTextureName("galaxycore:fragment_blue").setUnlocalizedName("blueClothingFragment");
        swordFragment = new AllPlainItems().setTextureName("galaxycore:fragment_sword").setUnlocalizedName("swordFragment");
        redClothingFragment = new AllPlainItems().setTextureName("galaxycore:fragment_red").setUnlocalizedName("redClotingFragment");
        armorFragment = new AllPlainItems().setTextureName("galaxycore:fragment_armor").setUnlocalizedName("armorFragment");
        brokenChip = new AllPlainItems().setTextureName("galaxycore:chip_break").setUnlocalizedName("brokenChip");
        brokenProcessor = new AllPlainItems().setTextureName("galaxycore:proccesor_reak").setUnlocalizedName("brokenProcessor");
        esfera = new AllPlainItems().setTextureName("galaxycore:esfera").setUnlocalizedName("Esfera");
        galaxyIngot = new GalaxyIngot().setTextureName("galaxycore:mineral").setUnlocalizedName("GalaxyIngot").setCreativeTab(CreativeTabs.tabMaterials);
        galaxyOre = new GalaxyOre(Material.rock);
        skeletonOre = new SkeletonOre(Material.rock);
        AranaOre = new AranaOre(Material.rock);
        BrujaOre = new BrujaOre(Material.rock);
        BlazeOre = new BlazeOre(Material.rock);
        CreeperOre = new CerdoOre(Material.rock);
        EndermanOre = new EndermanOre(Material.rock);
        CerdoOre = new CerdoOre(Material.rock);
        GhastOre = new GhastOre(Material.rock);
        FantasmaOre = new FantasmaOre(Material.rock);
        MagmaOre = new MagmaOre(Material.rock);
        WhiterOre = new WhiterOre(Material.rock);
        MurcielagoOre = new MurcielagoOre(Material.rock);
        OvejaOre = new OvejaOre(Material.rock);
        PigmanOre = new PigmanOre(Material.rock);
        SlimeOre = new SlimeOre(Material.rock);
        VacaOre = new VacaOre(Material.rock);
        VacaIngot = new VacaIngot().setTextureName("galaxycore:vaca_ingot").setUnlocalizedName("VacaIngot").setCreativeTab(CreativeTabs.tabMaterials);
        SlimeIngot = new SlimeIngot().setTextureName("galaxycore:slime_ingot").setUnlocalizedName("SlimeIngot").setCreativeTab(CreativeTabs.tabMaterials);
        PigmanIngot = new PigmanIngot().setTextureName("galaxycore:pigman_ingot").setUnlocalizedName("PigmanIngot").setCreativeTab(CreativeTabs.tabMaterials);
        OvejaIngot = new OvejaIngot().setTextureName("galaxycore:oveja_ingot").setUnlocalizedName("OvejaIngot").setCreativeTab(CreativeTabs.tabMaterials);
        MurcielagoIngot = new MurcielagoIngot().setTextureName("galaxycore:murcielago_ingot").setUnlocalizedName("MurcielagoIngot").setCreativeTab(CreativeTabs.tabMaterials);
        WhiterIngot = new WhiterIngot().setTextureName("galaxycore:whiter_ingot").setUnlocalizedName("WhiterIngot").setCreativeTab(CreativeTabs.tabMaterials);
        GhastIngot = new GhastIngot().setTextureName("galaxycore:ghast_ingot").setUnlocalizedName("GhastIngot").setCreativeTab(CreativeTabs.tabMaterials);
        FantasmaIngot = new FantasmaIngot().setTextureName("galaxycore:fantasma_ingot").setUnlocalizedName("FantasmaIngot").setCreativeTab(CreativeTabs.tabMaterials);
        MagmaIngot = new MagmaIngot().setTextureName("galaxycore:magma_ingot").setUnlocalizedName("MagmaIngot").setCreativeTab(CreativeTabs.tabMaterials);
        CerdoIngot = new CerdoIngot().setTextureName("galaxycore:cerdo_ingot").setUnlocalizedName("CerdoIngot").setCreativeTab(CreativeTabs.tabMaterials);
        EndermanIngot = new EndermanIngot().setTextureName("galaxycore:enderman_ingot").setUnlocalizedName("EndermanIngot").setCreativeTab(CreativeTabs.tabMaterials);
        CreeperIngot = new CreeperIngot().setTextureName("galaxycore:creeper_ingot").setUnlocalizedName("CreeperIngot").setCreativeTab(CreativeTabs.tabMaterials);
        BlazeIngot = new BlazeIngot().setTextureName("galaxycore:blaze_ingot").setUnlocalizedName("BlazeIngot").setCreativeTab(CreativeTabs.tabMaterials);
        BrujaIngot = new BrujaIngot().setTextureName("galaxycore:bruja_ingot").setUnlocalizedName("BrujaIngot").setCreativeTab(CreativeTabs.tabMaterials);
        AranaIngot = new AranaIngot().setTextureName("galaxycore:arana_ingot").setUnlocalizedName("AranaIngot").setCreativeTab(CreativeTabs.tabMaterials);
        skeletonIngot = new SkeletonIngot().setTextureName("galaxycore:skeleton_ingot").setUnlocalizedName("SkeletonIngot").setCreativeTab(CreativeTabs.tabMaterials);
        mixedIngot = new MixedIngot().setTextureName("galaxycore:mineral_4").setUnlocalizedName("MixedIngot").setCreativeTab(CreativeTabs.tabMaterials);

        GameRegistry.registerBlock(mixedOre = new MixedOre(Material.rock), "mixedOre");
        GameRegistry.registerItem(sageInsectSoup, "sageInsectSoup");
        GameRegistry.registerItem(scytheHidani, "scytheHidani");
        GameRegistry.registerItem(shakujoObitoMadara, "shakujoObitoMadara");
        GameRegistry.registerItem(shakujoObito,  "shakujoObito");
        GameRegistry.registerItem(woodKatana, "woodKatana");
        GameRegistry.registerItem(arakBoots, "arakBoots");
        GameRegistry.registerItem(arakLegs, "arakLegs");
        GameRegistry.registerItem(arakChest, "arakChest");
        GameRegistry.registerItem(babyVegetaBoots, "babyvegetaBoots");
        GameRegistry.registerItem(babyVegetaChest, "babyvegetaChest");
        GameRegistry.registerItem(babyVegetaLegs, "babyvegetaLegs");
        GameRegistry.registerItem(champaBoots, "champaBoots");
        GameRegistry.registerItem(champaLegs, "champaLegs");
        GameRegistry.registerItem(champaChest, "champaChest");
        GameRegistry.registerItem(chiraiBoots, "chiraiBoots");
        GameRegistry.registerItem(chiraiChest, "chiraiChest");
        GameRegistry.registerItem(chiraiLegs, "chiraiLegs");
        GameRegistry.registerItem(daishinkanBoots, "daishinkanBoots");
        GameRegistry.registerItem(daishinkanChest, "daishinkanChest");
        GameRegistry.registerItem(daishinkanLegs, "daishinkanLegs");
        GameRegistry.registerItem(fuBoots, "fuBoots");
        GameRegistry.registerItem(fuLegs, "fuLegs");
        GameRegistry.registerItem(fuChest, "fuChest");
        GameRegistry.registerItem(gogetaBoots, "gogetaBoots");
        GameRegistry.registerItem(gogetaChest, "gogetaChest");
        GameRegistry.registerItem(gogetaLegs, "gogetaLegs");
        GameRegistry.registerItem(kambaBoots, "kambaBoots");
        GameRegistry.registerItem(kambaChest, "kambaChest");
        GameRegistry.registerItem(kambaLegs, "kambaLegs");
        GameRegistry.registerItem(shallotBoots, "shallotBoots");
        GameRegistry.registerItem(shallotChest, "shallotChest");
        GameRegistry.registerItem(shallotLegs, "shallotLegs");
        GameRegistry.registerItem(trunksABoots, "trunksABoots");
        GameRegistry.registerItem(trunksAChest, "trunksAChest");
        GameRegistry.registerItem(trunksALegs, "trunksALegs");
        GameRegistry.registerItem(trunksBBoots, "trunksBBoots");
        GameRegistry.registerItem(trunksBChest, "trunksBChest");
        GameRegistry.registerItem(trunksBLegs, "trunksBLegs");
        GameRegistry.registerItem(trunksCBoots, "trunksCBoots");
        GameRegistry.registerItem(trunksCChest, "trunksCChest");
        GameRegistry.registerItem(trunksCLegs, "trunksCLegs");
        GameRegistry.registerItem(yardratBoots, "yardratBoots");
        GameRegistry.registerItem(yardratLegs, "yardratLegs");
        GameRegistry.registerItem(yardratChest, "yardratChest");
        GameRegistry.registerItem(zenoSamaChest, "zenoSamaChest");
        GameRegistry.registerItem(zenoSamaLegs, "zenoSamaLegs");
        GameRegistry.registerItem(zenoSamaBoots, "zenoSamaBoots");
        GameRegistry.registerItem(MurcielagoIngot, "MurcielagoIngot");
        GameRegistry.registerBlock(MurcielagoOre, "MurcielagoOre");
        GameRegistry.registerItem(SlimeIngot, "SlimeIngot");
        GameRegistry.registerBlock(SlimeOre, "SlimeOre");
        GameRegistry.registerBlock(OvejaOre, "OvejaOre");
        GameRegistry.registerItem(OvejaIngot, "OvejaIngot");
        GameRegistry.registerItem(PigmanIngot, "PigmanIngot");
        GameRegistry.registerBlock(PigmanOre, "PigmanOre");
        GameRegistry.registerItem(WhiterIngot, "WhiterIngot");
        GameRegistry.registerBlock(WhiterOre, "WhiterOre");
        GameRegistry.registerBlock(GhastOre, "GhastOre");
        GameRegistry.registerItem(GhastIngot, "GhastIngot");
        GameRegistry.registerItem(FantasmaIngot, "FantasmaIngot");
        GameRegistry.registerBlock(FantasmaOre, "FantasmaOre");
        GameRegistry.registerBlock(MagmaOre, "MagmaOre");
        GameRegistry.registerItem(MagmaIngot, "MagmaIngot");
        GameRegistry.registerItem(CerdoIngot, "CerdoIngot");
        GameRegistry.registerBlock(CerdoOre, "CerdoOre");
        GameRegistry.registerItem(EndermanIngot, "EndermanIngot");
        GameRegistry.registerBlock(EndermanOre, "EndermanOre");
        GameRegistry.registerItem(CreeperIngot, "CreeperIngot");
        GameRegistry.registerBlock(CreeperOre, "CreeperOre");
        GameRegistry.registerItem(AranaIngot, "AranaIngot");
        GameRegistry.registerBlock(AranaOre, "AranaOre");
        GameRegistry.registerBlock(BlazeOre, "BlazeOre");
        GameRegistry.registerItem(BlazeIngot, "BlazeIngot");
        GameRegistry.registerBlock(BrujaOre, "BrujaOre");
        GameRegistry.registerItem(BrujaIngot, "BrujaIngot");
        GameRegistry.registerItem(mixedIngot, "mixedIngot");
        GameRegistry.registerBlock(galaxyOre, "galaxyOre");
        GameRegistry.registerBlock(skeletonOre, "skeletonOre");
        GameRegistry.registerItem(skeletonIngot, "skeletonIngot");
        GameRegistry.registerItem(allXP, "allXP");
        GameRegistry.registerItem(whissSword, "whissSword");
        GameRegistry.registerItem(galaxyIngot, "galaxyIngot");
        GameRegistry.registerItem(combatXP, "combatXP");
        GameRegistry.registerItem(colossalXP, "colossalXP");
        GameRegistry.registerItem(yellowRock, "yellowRock");
        GameRegistry.registerItem(grandBottle, "grandBottle");
        GameRegistry.registerItem(capsula1, "capsula1");
        GameRegistry.registerItem(capsula2, "capsula2");
        GameRegistry.registerItem(capsula3, "capsula3");
        GameRegistry.registerItem(capsula4, "capsula4");
        GameRegistry.registerItem(brokenChip, "brokenChip");
        GameRegistry.registerItem(swordFragment, "swordFragment");
        GameRegistry.registerItem(redClothingFragment, "redClothingFragment");
        GameRegistry.registerItem(blueClothingFragment, "blueClothingFragment");
        GameRegistry.registerItem(redClothingFragment, "redClothingFragment");
        GameRegistry.registerItem(brokenProcessor, "brokenProcessor");
        GameRegistry.registerItem(armorFragment, "armorFragment");
        GameRegistry.registerItem(esfera, "esfera");
        GameRegistry.registerItem(calabazaChest, "calabazaChest");
        GameRegistry.registerItem(calabazaLegs, "calabazaLegs");
        GameRegistry.registerItem(calabazaBoots, "calabazaBoots");
        GameRegistry.registerItem(calabazaHelmet, "calabazaHelmet");
        GameRegistry.registerItem(scaryChest, "scaryChest");
        GameRegistry.registerItem(scaryLegs, "scaryLegs");
        GameRegistry.registerItem(scaryBoots, "scaryBoots");
        GameRegistry.registerItem(espadalapizlazuli, "espadalapizlazuli");
        GameRegistry.registerItem(scaryHelmet, "scaryHelmet");
        GameRegistry.registerItem(skeletonChest, "skeletonChest");
        GameRegistry.registerItem(itChest, "itChest");
        GameRegistry.registerItem(itBoots, "itLegs");
        GameRegistry.registerItem(itHelmet, "itBoots");
        GameRegistry.registerItem(itLegs, "itHelmet");
        GameRegistry.registerItem(trunksChest, "trunksChest");
        GameRegistry.registerItem(trunksBoots, "trunksBoots");
        GameRegistry.registerItem(trunksLegs, "trunksLegs");
        GameRegistry.registerItem(skeletonLegs, "skeletonLegs");
        GameRegistry.registerItem(skeletonBoots, "skeletonBoots");
        GameRegistry.registerItem(skeletonHelmet, "skeletonHelmet");
        GameRegistry.registerItem(zombiePickaxe, "zombiePickaxe");
        GameRegistry.registerItem(steelPickaxe, "steelPickaxe");
        GameRegistry.registerItem(steelAxe, "steelAxe");
        GameRegistry.registerItem(raiderAxe, "raiderAxe");
        GameRegistry.registerItem(espadaacero, "espadacero");
        GameRegistry.registerItem(cuchillaacero, "cuchillaacero");
        GameRegistry.registerItem(jungleAxe, "jungleAxe");
        GameRegistry.registerItem(blazeBoots, "blazeBoots");
        GameRegistry.registerItem(blazeLegs, "blazeLegs");
        GameRegistry.registerItem(blazeChest, "blazeChest");
        GameRegistry.registerItem(covidChest, "covidChest");
        GameRegistry.registerItem(covidBoots, "covidBoots");
        GameRegistry.registerItem(covidLegs, "covidLegs");
        GameRegistry.registerItem(covidHelmet, "covidHelmet");
        GameRegistry.registerItem(tropaHelmet, "tropaHelmet");
        GameRegistry.registerItem(tropaBoots, "tropaBoots");
        GameRegistry.registerItem(tropaLegs, "tropaLegs");
        GameRegistry.registerItem(tropaChest, "tropaChest");
        GameRegistry.registerItem(emeraldBlade, "emeraldBlade");
        GameRegistry.registerItem(earthShard, "earthShard");
        GameRegistry.registerItem(galaxySword, "galaxySword");
        GameRegistry.registerItem(crystalHelmet, "crystalHelmet");
        GameRegistry.registerItem(crystalBoots, "crystalBoots");
        GameRegistry.registerItem(crystalLegs, "crystalLegs");
        GameRegistry.registerItem(crystalChest, "crystalChest");
        GameRegistry.registerItem(magmaHelmet, "magmaHelmet");
        GameRegistry.registerItem(magmaBoots, "magmaBoots");
        GameRegistry.registerItem(magmaLegs, "magmaLegs");
        GameRegistry.registerItem(Daga, "Daga");
        GameRegistry.registerItem(Azada, "Azada");
        GameRegistry.registerItem(magmaChest, "magmaChest");
        GameRegistry.registerItem(AxeHalloween, "AxeHalloween");
        GameRegistry.registerItem(TridenteHalloween, "TridenteHalloween");
        GameRegistry.registerItem(dragonslayerBoots, "dragonslayerBoots");
        GameRegistry.registerItem(dragonslayerLegs, "dragonslayerLegs");
        GameRegistry.registerItem(dragonslayerChest, "dragonslayerChest");
        GameRegistry.registerItem(protectorHelmet, "protectorHelmet");
        GameRegistry.registerItem(protectorBoots, "protectorBoots");
        GameRegistry.registerItem(protectorLegs, "protectorLegs");
        GameRegistry.registerItem(protectorChest, "protectorChest");
        mjolnir = GameRegistry.registerItem(new ItemSword2(Item.ToolMaterial.EMERALD).setCreativeTab(CreativeTabs.tabMaterials).setMaxStackSize(1).setMaxDamage(100).setTextureName("galaxycore:combat_xp").setUnlocalizedName("mjolnir"), "mjolnir", "galaxycore");
        mandoblemodel = GameRegistry.registerItem(new ItemSword2(Item.ToolMaterial.EMERALD).setCreativeTab(CreativeTabs.tabMaterials).setMaxStackSize(1).setMaxDamage(100).setTextureName("galaxycore:mandoble").setUnlocalizedName("Mandoble"), "Mandoble", "galaxycore");
        hachamodel = GameRegistry.registerItem(new ItemSword2(Item.ToolMaterial.EMERALD).setCreativeTab(CreativeTabs.tabMaterials).setMaxStackSize(1).setMaxDamage(100).setTextureName("galaxycore:hachamodel").setUnlocalizedName("Hacha Model"), "Hacha Model", "galaxycore");
        stormbreaker = GameRegistry.registerItem(new ItemSword2(Item.ToolMaterial.EMERALD).setCreativeTab(CreativeTabs.tabMaterials).setMaxStackSize(1).setMaxDamage(100).setTextureName("galaxycore:stormbreaker").setUnlocalizedName("stormbreaker"), "stormbreaker", "galaxycore");
        espadasparrow = GameRegistry.registerItem(new ItemSword2(Item.ToolMaterial.EMERALD).setCreativeTab(CreativeTabs.tabMaterials).setMaxStackSize(1).setMaxDamage(100).setTextureName("galaxycore:espadasparrow").setUnlocalizedName("espadasparrow"), "espadasparrow", "galaxycore");
        picomodel = GameRegistry.registerItem(new ItemSword2(Item.ToolMaterial.EMERALD).setCreativeTab(CreativeTabs.tabMaterials).setMaxStackSize(1).setMaxDamage(100).setTextureName("galaxycore:picomodel").setUnlocalizedName("picomodel"), "picomodel", "galaxycore");
        EspadaGalaxy = GameRegistry.registerItem(new ItemSword2(Item.ToolMaterial.EMERALD).setCreativeTab(CreativeTabs.tabMaterials).setMaxStackSize(1).setMaxDamage(100).setTextureName("galaxycore:espadagalaxy2").setUnlocalizedName("espadagalaxy2"), "espadagalaxy2", "galaxycore");
        cubito = GameRegistry.registerItem(new ArmorTest(testArmorMaterial, 0, "cubito", "cubito"), "cubito", "galaxycore");
        Lanza = GameRegistry.registerItem(new ItemSword2(Item.ToolMaterial.EMERALD).setCreativeTab(CreativeTabs.tabMaterials).setMaxStackSize(1).setMaxDamage(100).setTextureName("galaxycore:lanza").setUnlocalizedName("lanza"), "lanza", "galaxycore");
        PiruletaHalloween = GameRegistry.registerItem(new ItemSword2(Item.ToolMaterial.EMERALD).setCreativeTab(CreativeTabs.tabMaterials).setMaxStackSize(1).setMaxDamage(100).setTextureName("galaxycore:piruleta_halloween").setUnlocalizedName("piruletahalloween"), "piruletahalloween", "galaxycore");
        ColmilloDragon = GameRegistry.registerItem(new ItemSword2(Item.ToolMaterial.EMERALD).setCreativeTab(CreativeTabs.tabMaterials).setMaxStackSize(1).setMaxDamage(500).setTextureName("galaxycore:ColmilloDragon").setUnlocalizedName("Colmillo Dragon"), "Colmillo Dragon", "galaxycore");
        table = GameRegistry.registerBlock(new BlockTable().setCreativeTab(CreativeTabs.tabMaterials).setBlockTextureName("galaxycore:table").setBlockName("block"), "table");
        pilararriba = GameRegistry.registerBlock(new BlockPilarA().setCreativeTab(CreativeTabs.tabMaterials).setBlockTextureName("galaxycore:pilararriba").setBlockName("pilararriba"), "pilararriba");
        pilarabajo = GameRegistry.registerBlock(new BlockPilarB().setCreativeTab(CreativeTabs.tabMaterials).setBlockTextureName("galaxycore:pilarabajo").setBlockName("pilarabajo"), "pilarabajo");
        GameRegistry.registerTileEntity(TileEntityTable.class, "0");
        GameRegistry.registerTileEntity(TileEntityPilarA.class, "1");
        GameRegistry.registerTileEntity(TileEntityPilarB.class, "2");
        GameRegistry.registerTileEntity(TileEntityPilarC.class, "3");
    }

    @SideOnly(Side.CLIENT)
    public static void render() {
        MinecraftForgeClient.registerItemRenderer(mjolnir, new MjolnirThorRender());
        MinecraftForgeClient.registerItemRenderer(mandoblemodel, new MandobleRender());
        MinecraftForgeClient.registerItemRenderer(hachamodel, new HachaRender());
        MinecraftForgeClient.registerItemRenderer(espadasparrow, new EspadaSparrowRender());
        MinecraftForgeClient.registerItemRenderer(EspadaGalaxy, new EspadaRender());
        MinecraftForgeClient.registerItemRenderer(PiruletaHalloween, new PiruletaHalloweenRender());
        MinecraftForgeClient.registerItemRenderer(Lanza, new LanzaRender());
        MinecraftForgeClient.registerItemRenderer(picomodel, new PicoRender());
        MinecraftForgeClient.registerItemRenderer(stormbreaker, new StormBreakerRender());
        MinecraftForgeClient.registerItemRenderer(ColmilloDragon, new ColmilloRender());
        ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPilarB.class, new PilarAbajoRender(new PilarAbajoModel(), "pilarabajo"));
        ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTable.class, new RenderTable(new TableModel(), "table"));
        ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPilarA.class, new PilarArribaRender(new PilarArribaModel(), "pilararriba"));
        ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPilarC.class, new PilarMedioRender(new PilarMedioModel(), "pilarmedio"));
    }

    static {
        testArmorMaterial = EnumHelper.addArmorMaterial("testArmorMaterial", Integer.MAX_VALUE, new int[] { 3, 8, 6, 3 }, 30);
        testToolMaterial = EnumHelper.addToolMaterial("testToolMaterial", 3, Integer.MAX_VALUE, 8.0f, 3.0f, 30);
    }

    public static ItemArmor.ArmorMaterial setArmor(int durability) {
        int name = 0;
        ItemArmor.ArmorMaterial ARMOR = EnumHelper.addArmorMaterial("" + name++, durability, new int[]{3, 8, 6, 3}, 30);
        return ARMOR;
    }
}